services:
  stats-server:
    build:
      context: .
      dockerfile: ewm-stats-service/Dockerfile
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - stats-db

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stats
    ports:
      - "5432:5432"
    volumes:
      - stats-db-data:/var/lib/postgresql/data

  ewm-service:
    build:
      context: .
      dockerfile: ewm-main-service/Dockerfile
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1

volumes:
  stats-db-data:
  ewm-db-data: