DROP TABLE IF EXISTS endpoint_hit;

CREATE TABLE endpoint_hit (
  id BIGSERIAL PRIMARY KEY,
  app VARCHAR(255) NOT NULL,
  uri VARCHAR(2000) NOT NULL,
  ip VARCHAR(50) NOT NULL,
  timestamp TIMESTAMP NOT NULL
);