server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: never

logging:
  level:
    root: INFO

stats-service:
  url: http://stats-server:9090

app:
  name: ewm-main-service